from enum import Enum
from dataclasses import dataclass

@dataclass
class CountryStruct:
    name: str
    alpha_2: str 

class Country(Enum):
    Albania: CountryStruct = CountryStruct("Albania", "AL")
    Andorra: CountryStruct = CountryStruct("Andorra", "AD")
    Argentina: CountryStruct = CountryStruct("Argentina", "AR")
    Australia: CountryStruct = CountryStruct("Australia", "AU")
    Austria: CountryStruct = CountryStruct("Austria", "AT")
    Bangladesh: CountryStruct = CountryStruct("Bangladesh", "BD")
    Belgium: CountryStruct = CountryStruct("Belgium", "BE")
    Bermuda: CountryStruct = CountryStruct("Bermuda", "BM")
    Bhutan: CountryStruct = CountryStruct("Bhutan", "BT")
    Botswana: CountryStruct = CountryStruct("Botswana", "BW")
    Brazil: CountryStruct = CountryStruct("Brazil", "BR")
    Bulgaria: CountryStruct = CountryStruct("Bulgaria", "BG")
    Cambodia: CountryStruct = CountryStruct("Cambodia", "KH")
    Canada: CountryStruct = CountryStruct("Canada", "CA")
    Chile: CountryStruct = CountryStruct("Chile", "CL")
    China: CountryStruct = CountryStruct("China", "CN")
    Colombia: CountryStruct = CountryStruct("Colombia", "CO")
    Croatia: CountryStruct = CountryStruct("Croatia", "HR")
    Denmark: CountryStruct = CountryStruct("Denmark", "DK")
    DominicanRepublic: CountryStruct = CountryStruct("Dominican Republic", "DO")
    Ecuador: CountryStruct = CountryStruct("Ecuador", "EC")
    Estonia: CountryStruct = CountryStruct("Estonia", "EE")
    Finland: CountryStruct = CountryStruct("Finland", "FI")
    France: CountryStruct = CountryStruct("France", "FR")
    Germany: CountryStruct = CountryStruct("Germany", "DE")
    Ghana: CountryStruct = CountryStruct("Ghana", "GH")
    Greece: CountryStruct = CountryStruct("Greece", "GR")
    Greenland: CountryStruct = CountryStruct("Greenland", "GL")
    Guam: CountryStruct = CountryStruct("Guam", "GU")
    Guatemala: CountryStruct = CountryStruct("Guatemala", "GT")
    Hungary: CountryStruct = CountryStruct("Hungary", "HU")
    Iceland: CountryStruct = CountryStruct("Iceland", "IS")
    India: CountryStruct = CountryStruct("India", "IN")
    Indonesia: CountryStruct = CountryStruct("Indonesia", "ID")
    Ireland: CountryStruct = CountryStruct("Ireland", "IE")
    Israel: CountryStruct = CountryStruct("Israel", "IL")
    Italy: CountryStruct = CountryStruct("Italy", "IT")
    Japan: CountryStruct = CountryStruct("Japan", "JP")
    Jordan: CountryStruct = CountryStruct("Jordan", "JO")
    Kenya: CountryStruct = CountryStruct("Kenya", "KE")
    Kyrgyzstan: CountryStruct = CountryStruct("Kyrgyzstan", "KG")
    Latvia: CountryStruct = CountryStruct("Latvia", "LV")
    Lesotho: CountryStruct = CountryStruct("Lesotho", "LS")
    Lithuania: CountryStruct = CountryStruct("Lithuania", "LT")
    Luxembourg: CountryStruct = CountryStruct("Luxembourg", "LU")
    Madagascar: CountryStruct = CountryStruct("Madagascar", "MG")
    Malaysia: CountryStruct = CountryStruct("Malaysia", "MY")
    Malta: CountryStruct = CountryStruct("Malta", "MT")
    Mexico: CountryStruct = CountryStruct("Mexico", "MX")
    Monaco: CountryStruct = CountryStruct("Monaco", "MC")
    Mongolia: CountryStruct = CountryStruct("Mongolia", "MN")
    Montenegro: CountryStruct = CountryStruct("Montenegro", "ME")
    Netherlands: CountryStruct = CountryStruct("Netherlands", "NL")
    NewZealand: CountryStruct = CountryStruct("New Zealand", "NZ")
    Nigeria: CountryStruct = CountryStruct("Nigeria", "NG")
    Norway: CountryStruct = CountryStruct("Norway", "NO")
    Pakistan: CountryStruct = CountryStruct("Pakistan", "PK")
    Peru: CountryStruct = CountryStruct("Peru", "PE")
    Philippines: CountryStruct = CountryStruct("Philippines", "PH")
    Poland: CountryStruct = CountryStruct("Poland", "PL")
    Portugal: CountryStruct = CountryStruct("Portugal", "PT")
    PuertoRico: CountryStruct = CountryStruct("Puerto Rico", "PR")
    Romania: CountryStruct = CountryStruct("Romania", "RO")
    Rwanda: CountryStruct = CountryStruct("Rwanda", "RW")
    Senegal: CountryStruct = CountryStruct("Senegal", "SN")
    Serbia: CountryStruct = CountryStruct("Serbia", "RS")
    Singapore: CountryStruct = CountryStruct("Singapore", "SG")
    Slovakia: CountryStruct = CountryStruct("Slovakia", "SK")
    Slovenia: CountryStruct = CountryStruct("Slovenia", "SI")
    SouthAfrica: CountryStruct = CountryStruct("South Africa", "ZA")
    Spain: CountryStruct = CountryStruct("Spain", "ES")
    SriLanka: CountryStruct = CountryStruct("Sri Lanka", "LK")
    Sweden: CountryStruct = CountryStruct("Sweden", "SE")
    Switzerland: CountryStruct = CountryStruct("Switzerland", "CH")
    Thailand: CountryStruct = CountryStruct("Thailand", "TH")
    Tunisia: CountryStruct = CountryStruct("Tunisia", "TN")
    Turkey: CountryStruct = CountryStruct("Turkey", "TR")
    Uganda: CountryStruct = CountryStruct("Uganda", "UG")
    Ukraine: CountryStruct = CountryStruct("Ukraine", "UA")
    UnitedArabEmirates: CountryStruct = CountryStruct("United Arab Emirates", "AE")
    UnitedKingdom: CountryStruct = CountryStruct("United Kingdom", "GB")
    UnitedStates: CountryStruct = CountryStruct("United States", "US")
    Uruguay: CountryStruct = CountryStruct("Uruguay", "UY")
    Taiwan: CountryStruct = CountryStruct("Taiwan", "TW")
    SouthKorea: CountryStruct = CountryStruct("South Korea", "KR")
    Russia: CountryStruct = CountryStruct("Russia", "RU")
    Palestine: CountryStruct = CountryStruct("Palestine", "PS")
    Laos: CountryStruct = CountryStruct("Laos", "LA")
    Vietnam: CountryStruct = CountryStruct("Vietnam", "VN")
    Bolivia: CountryStruct = CountryStruct("Bolivia", "BO")
    CzechRepublic: CountryStruct = CountryStruct("Czech Republic", "CZ")

    def __str__(self):
        return f'{self.value.name}'

